---
title: "HW4"
author: "Zach Steffens"
date: "2026-03-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dbplyr)
library(ggplot2)
library(lubridate)
```

```{r}
cars93 <- MASS::Cars93
ggplot(cars93, aes(x = Price, y = Fuel.tank.capacity)) +
geom_point(color = "grey60") +
geom_smooth(se = FALSE, method = "loess", formula = y ~ x, color = "#0072B2") +
scale_x_continuous(
name = "price (USD)",
breaks = c(20, 40, 60),
labels = c("$20,000", "$40,000", "$60,000")
) +
scale_y_continuous(name = "fuel-tank capacity\n(US gallons)")
```
Problem 4:
```{r}
library(ggplot2)
library(MASS)

cars93 <- MASS::Cars93

ggplot(cars93, aes(x = Price, y = Fuel.tank.capacity)) +
  geom_point(color = "grey60") +
  geom_smooth(
    se = TRUE,
    method = "lm",
    formula = y ~ x,
    color = "#8fe388"
  ) +
  ggtitle("Linear Model (lm) Smoother") +
  theme(
    plot.title = element_text(size = 14, color = "#8fe388")
  ) +
  scale_x_continuous(
    name = "price (USD)",
    breaks = c(20, 40, 60),
    labels = c("$20,000", "$40,000", "$60,000")
  ) +
  scale_y_continuous(name = "fuel-tank capacity\n(US gallons)")

ggplot(cars93, aes(x = Price, y = Fuel.tank.capacity)) +
  geom_point(color = "grey60") +
  geom_smooth(
    se = TRUE,
    method = "glm",
    formula = y ~ x,
    color = "#fe8d6d"
  ) +
  ggtitle("Generalized Linear Model (glm) Smoother") +
  theme(
    plot.title = element_text(size = 14, color = "#fe8d6d")
  ) +
  scale_x_continuous(
    name = "price (USD)",
    breaks = c(20, 40, 60),
    labels = c("$20,000", "$40,000", "$60,000")
  ) +
  scale_y_continuous(name = "fuel-tank capacity\n(US gallons)")

library(mgcv)

ggplot(cars93, aes(x = Price, y = Fuel.tank.capacity)) +
  geom_point(color = "grey60") +
  geom_smooth(
    se = TRUE,
    method = "gam",
    formula = y ~ s(x),
    color = "#7c6bea"
  ) +
  ggtitle("Generalized Additive Model (gam) Smoother") +
  theme(
    plot.title = element_text(size = 14, color = "#7c6bea")
  ) +
  scale_x_continuous(
    name = "price (USD)",
    breaks = c(20, 40, 60),
    labels = c("$20,000", "$40,000", "$60,000")
  ) +
  scale_y_continuous(name = "fuel-tank capacity\n(US gallons)")
```
```{r}
load("C:\\Users\\zrsm9\\OneDrive\\Documents\\MS Data Analytics\\CSC587\\DATA\\preprint_growth.rda") 
head(preprint_growth)
preprint_growth %>% filter(archive == "bioRxiv") %>%
filter(count > 0) -> biorxiv_growth
preprints<-preprint_growth %>% filter(archive %in%
c("bioRxiv", "arXiv q-bio", "PeerJ Preprints")) %>%filter(count > 0) %>%
mutate(archive = factor(archive, levels = c("bioRxiv", "arXiv q-bio", "PeerJ Preprints")))
preprints_final <- filter(preprints, date == ymd("2017-01-01"))

ggplot(preprints) +
aes(date, count, color = archive, fill = archive) +
geom_line(size = 1) +
scale_y_continuous(
limits = c(0, 600), expand = c(0, 0),
name = "preprints / month",
sec.axis = dup_axis( #this part is for the second y axis
breaks = preprints_final$count, #and we use the counts to position our labels
labels = c("arXivq-bio", "PeerJPreprints", "bioRxiv"),
name = NULL)
) +
scale_x_date(name = "year",
limits = c(min(biorxiv_growth$date), ymd("2017-01-01"))) +
scale_color_manual(values = c("#0072b2", "#D55E00", "#009e73"),
name = NULL) +
theme(legend.position = "none")
```
Problem 2:
```{r}
#a)
library(dplyr)
library(tidyr)
library(ggplot2)

preprint_full <- preprint_growth %>%
  drop_na() %>%
  filter(count > 0) %>%
  filter(year(date) > 2004)

#b)
preprints_two <- preprint_full %>%
  filter(archive %in% c("bioRxiv", "F1000Research"))

#c-f)
ggplot(preprints_two, aes(x = date, y = count, color = archive)) +
  geom_line(size = 1) +
  scale_color_manual(
    values = c(
      "bioRxiv" = "#7c6bea",
      "F1000Research" = "#fe8d6d"
    ),
    name = NULL
  ) +
  scale_x_date(
    name = "Year",
    limits = c(ymd("2014-02-01"), max(preprints_two$date))
  ) +
  scale_y_continuous(name = "Preprints / Month") +
  ggtitle("Preprint Counts") +
  theme(
    legend.position = "right",
    plot.title = element_text(size = 14, face = "bold")
  )

```

